Update examples
w3c-ccg/universal-wallet-interop-spec pull request #61
Opened 2021-03-15 19:18 UTC by OR13

2021-03-15 19:36 UTC, mprorock approved these changes

2021-03-16 17:45 UTC, kimdhamilton approved these changes

2021-03-16 20:07 UTC, TallTed requested changes

2021-03-16 20:07 UTC, TallTed commented on docs/index.html
> +      "marketingAuthorizationHolder": "Moderna Biotech"
I think these would be better as made-up values, without reference to any real entity.
```suggestion
      "disease": "Example Virus",
      "atcCode": "J07BX03",
      "medicinalProductName": "Example Vaccine Example Biotech",
      "marketingAuthorizationHolder": "Example Biotech"
```

2021-03-16 20:07 UTC, TallTed commented on docs/index.html
> +  "description": "COVID-19 Vaccination Certificate",
```suggestion
  "name": "Example Virus Vaccination Certificate",
  "description": "Example Virus Vaccination Certificate",
```

2021-03-16 20:07 UTC, TallTed commented on docs/examples/vaccination-event-credential-example.json
> +      "marketingAuthorizationHolder": "Moderna Biotech"
```suggestion
      "disease": "Example Virus",
      "atcCode": "J07BX03",
      "medicinalProductName": "Example Virus Vaccine Example Biotech",
      "marketingAuthorizationHolder": "Example Biotech"
```

2021-03-16 20:07 UTC, TallTed commented on docs/examples/vaccination-event-credential-example.json
> +  "description": "COVID-19 Vaccination Certificate",
```suggestion
  "name": "Example Virus Vaccination Certificate",
  "description": "Example Virus Vaccination Certificate",
```

2021-03-17 18:15 UTC, OR13 commented
@TallTed this example is pulled from https://github.com/w3c-ccg/vaccination-vocab and your changes would break the signature.

2021-03-17 19:57 UTC, TallTed commented
*sighs* I guess I'll poke there now...

2021-03-18 16:16 UTC, merged