Add informative content
w3c-ccg/universal-wallet-interop-spec pull request #80
Opened 2021-03-21 16:18 UTC by OR13

describe general types of wallets and cloud secret managers

2021-03-23 18:55 UTC, kimdhamilton approved these changes

2021-03-25 01:48 UTC, kimdhamilton commented
pinging @NTonani and @mprorock for review; otherwise I think we can merge EOD tomorrow

2021-03-25 04:22 UTC, TallTed requested changes
Mostly typo fixes, some line length tweaks, increased consistency of acronym use...

2021-03-25 04:22 UTC, TallTed commented on docs/index.html
> +          PWA's don't require users to install an app throught an app store,
```suggestion
          PWAs don't require users to install an app through an app store, 
```

2021-03-25 04:22 UTC, TallTed commented on docs/index.html
> +          They can connect to remote api's to facilitate discovery and messaging.
```suggestion
          PWAs can access camera, WebRTC, NFC, Bluetooth, and other browser APIs. 
          They can connect to remote apis to facilitate discovery and messaging.
```

2021-03-25 04:22 UTC, TallTed commented on docs/index.html
> +          Native Mobile Applications are software a user installs on a mobile OS, like Android or iOS.
```suggestion
          Native Mobile Applications (NMAs) are software a user installs on a mobile OS, like Android or iOS.
```

2021-03-25 04:22 UTC, TallTed commented on docs/index.html
> +          which might include filesystem, networking, phone, or camera APIs.
```suggestion
          NMAs have access to APIs supported by the mobile OS, such as 
          filesystem, network, phone, or camera APIs, among others.
```

2021-03-25 04:22 UTC, TallTed commented on docs/index.html
> +          This and better biometric authentication support make them attractive to high security applications.
```suggestion
          NMAs might implement support for hardware backed secret or key 
          management via the OS. This and better biometric authentication 
          support make them attractive to high security applications.
```

2021-03-25 04:22 UTC, TallTed commented on docs/index.html
> +          Cloud wallets can also be "always online", in cases where a mobile wallet might loose connectivity.
```suggestion
          Cloud wallets can also be "always online", in cases where a mobile wallet might lose connectivity.
```

2021-03-25 04:22 UTC, TallTed commented on docs/index.html
> +          Cloud wallets and message based APIs are generally an easier integration target with legacy systems.
```suggestion
          Cloud wallets and message based APIs are generally an easier integration target for legacy systems.
```

2021-03-25 04:22 UTC, TallTed commented on docs/index.html
> +          Cold storage wallets are non networked long term storage for digital assets.
```suggestion
          Cold Storage Wallets (CSWs) are non-networked, long-term storage for digital assets.
```

2021-03-25 04:22 UTC, TallTed commented on docs/index.html
> +          such as keys that control large amounts of crypto currency, or root certificate signing keys.
```suggestion
          Cold storage is typically reserved for very sensitive information, 
          such as keys that control large amounts of crypto currency, or root 
          certificate signing keys.
```

2021-03-25 04:22 UTC, TallTed commented on docs/index.html
> +          Cold storage wallets may be implemented as either isolated hardware or physical paper.
```suggestion
          CSWs may be implemented as either isolated hardware or physical paper.
```

2021-03-25 04:22 UTC, TallTed commented on docs/index.html
> +          Wallet's may use both managed asymmetric or symmetric key operations as well as managed and versioned secrets.
```suggestion
        <p class="note">
          Some services combine secret and key operations under the 
          umbrella term "Key Management Service".  Wallets may use both 
          managed asymmetric and symmetric key operations, as well as 
          managed and versioned secrets.
```

2021-03-25 22:50 UTC, NTonani approved these changes
_Very_ informative content!

2021-03-26 15:02 UTC, OR13 commented
@TallTed Thank you!

2021-03-30 20:28 UTC, merged