Add derive credential interface
w3c-ccg/universal-wallet-interop-spec pull request #82
Opened 2021-03-30 18:20 UTC by sudeshrshetty

added derive credential feature based on #81

2021-03-30 20:18 UTC, TallTed requested changes

2021-03-30 20:18 UTC, TallTed commented on docs/index.html
> +          <li><a href="https://w3c-ccg.github.io/ldp-bbs2020/#nonce">nonce </a> </li>
```suggestion
          <li><a href="https://w3c-ccg.github.io/ldp-bbs2020/#nonce">nonce</a></li>
```

2021-03-30 20:27 UTC, OR13 commented
@sudeshrshetty I will look to you to review @TallTed but this looks good to me. thanks!

2021-03-30 20:27 UTC, OR13 approved these changes

2021-03-30 20:28 UTC, OR13 commented
conflicts after recent merges

2021-03-31 03:18 UTC, sudeshrshetty commented on docs/index.html
> +          <li><a href="https://w3c-ccg.github.io/ldp-bbs2020/#nonce">nonce </a> </li>
fixed

2021-03-31 03:18 UTC, sudeshrshetty commented on docs/index.html
> +          <code>options</code> object.
fixed

2021-03-31 03:18 UTC, sudeshrshetty commented on docs/index.html
> +            let derivedCredential = wallet.derive(id, frame, options)
fixed

2021-03-31 03:30 UTC, sudeshrshetty commented
> conflicts after recent merges

@OR13  rebased

2021-03-31 14:01 UTC, OR13 approved these changes

2021-04-06 10:37 UTC, sudeshrshetty commented
@TallTed Can you please have a look at resolved comments?

2021-04-06 14:56 UTC, TallTed commented
@sudeshrshetty - They're fine.

2021-04-06 19:13 UTC, kimdhamilton approved these changes

2021-04-14 18:15 UTC, sudeshrshetty commented
@OR13 Can we merge this one?

2021-04-14 18:21 UTC, merged